language: r
dist: trusty
sudo: true
branches:
  only:
    - master


latex: false
pandoc_version: 2.3.1
before_install:
  - sudo apt-get update
r_packages:
  - bookdown
  - tinytex
  - ggplot2
r_github_packages:
  - r-lib/pkgdown
cache:
  packages: yes


# Travis build fails if commands in `script` throw errors
script:
  - echo "Hi"
  - R -e 'tinytex::install_tinytex()'
after_success:
  - R -e 'options(tinytex.verbose = TRUE); bookdown::render_book("index.Rmd", output_format = "bookdown::pdf_book")'
  - R -e 'bookdown::render_book("index.Rmd", output_format = "bookdown::gitbook")'
  - if [[ -d docs ]]; then rm -r docs; fi
  - mkdir docs
  - cp -r _book/* docs


# deploy `docs/` on branch:master to branch:gh-pages
deploy:
  - provider: pages     # Deploy to GitHub
    github-token: $GH_TOKEN  # personal access token
    skip-cleanup: true  # true, to keep the build results
    keep-history: false  # keep commit history on deployed branch?
    local-dir: docs  # dir to deploy after build
    on:
      branch: master  # Usaually set to the default branch of the repo
